"""Generate invoice PDF skill — create professional PDF invoices."""

import asyncio
import logging
import uuid
from datetime import date, timedelta
from typing import Any

from jinja2 import BaseLoader, Environment
from sqlalchemy import select

from src.core.context import SessionContext
from src.core.db import async_session
from src.core.models.contact import Contact
from src.core.models.enums import TransactionType
from src.core.models.transaction import Transaction
from src.core.observability import observe
from src.gateway.types import IncomingMessage
from src.skills._i18n import register_strings, t_cached
from src.skills.base import SkillResult

logger = logging.getLogger(__name__)

INVOICE_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; font-size: 14px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
  .company { font-size: 20px; font-weight: bold; color: #2c3e50; }
  .invoice-title { font-size: 28px; color: #3498db; text-align: right; }
  .invoice-number { color: #666; text-align: right; }
  .addresses { display: flex; justify-content: space-between; margin: 20px 0 30px; }
  .address-block { width: 45%; }
  .address-block h3 { color: #2980b9; margin-bottom: 5px; font-size: 12px;
                       text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #3498db; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #ddd; }
  .amount { text-align: right; }
  .total-row { font-weight: bold; background: #ebf5fb; }
  .total-amount { font-size: 18px; color: #2c3e50; }
  .footer { margin-top: 40px; font-size: 11px; color: #999;
            border-top: 1px solid #ddd; padding-top: 10px; }
  .due-date { color: #e74c3c; font-weight: bold; }
  .qr-section { text-align: center; margin-top: 20px; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="company">{{ company_name }}</div>
      {% if company_address %}<div>{{ company_address }}</div>{% endif %}
      {% if company_phone %}<div>{{ company_phone }}</div>{% endif %}
    </div>
    <div>
      <div class="invoice-title">INVOICE</div>
      <div class="invoice-number">#{{ invoice_number }}</div>
    </div>
  </div>

  <div class="addresses">
    <div class="address-block">
      <h3>Bill To</h3>
      <div><b>{{ client_name }}</b></div>
      {% if client_email %}<div>{{ client_email }}</div>{% endif %}
      {% if client_phone %}<div>{{ client_phone }}</div>{% endif %}
    </div>
    <div class="address-block">
      <h3>Invoice Details</h3>
      <div>Date: {{ invoice_date }}</div>
      <div class="due-date">Due: {{ due_date }}</div>
      <div>Currency: {{ currency }}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Description</th>
        <th>Date</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ item.description }}</td>
        <td>{{ item.date }}</td>
        <td class="amount">{{ "%.2f"|format(item.amount) }}</td>
      </tr>
      {% endfor %}
      <tr class="total-row">
        <td colspan="3"><b>Total</b></td>
        <td class="amount total-amount"><b>{{ currency_symbol }}{{ "%.2f"|format(total) }}</b></td>
      </tr>
    </tbody>
  </table>

  {% if notes %}
  <div style="margin-top: 20px;">
    <b>Notes:</b> {{ notes }}
  </div>
  {% endif %}

  <div class="footer">
    Generated by AI Assistant — {{ invoice_date }}
  </div>
</body>
</html>"""


_STRINGS = {
    "en": {
        "no_account": "Set up your account first to generate invoices.",
        "no_contact": 'Who should I invoice? Try: "generate invoice PDF for Mike Chen"',
        "contact_not_found": (
            'I don\'t have {name}\'s info. Add them first: "add contact {name}"'
        ),
        "no_transactions": (
            "No recent transactions found to include in the invoice. "
            "Add some income entries first."
        ),
        "pdf_failed": "Failed to generate PDF. Please try again.",
        "invoice_ready": (
            "\U0001f4c4 <b>Invoice #{number}</b>\n"
            "Client: {name}\n"
            "Total: {symbol}{total}\n"
            "Due: {due}"
        ),
    },
    "ru": {
        "no_account": "Сначала настройте аккаунт для создания инвойсов.",
        "no_contact": 'Кому выставить инвойс? Пример: "сделай PDF инвойс для Mike Chen"',
        "contact_not_found": (
            'У меня нет данных {name}. Сначала добавьте: "добавь контакт {name}"'
        ),
        "no_transactions": (
            "Нет недавних транзакций для инвойса. "
            "Сначала добавьте записи о доходах."
        ),
        "pdf_failed": "Не удалось создать PDF. Попробуйте снова.",
        "invoice_ready": (
            "\U0001f4c4 <b>Инвойс #{number}</b>\n"
            "Клиент: {name}\n"
            "Итого: {symbol}{total}\n"
            "Оплатить до: {due}"
        ),
    },
    "es": {
        "no_account": "Configure su cuenta primero para generar facturas.",
        "no_contact": 'A quien debo facturar? Ejemplo: "generar factura PDF para Mike Chen"',
        "contact_not_found": (
            'No tengo la informacion de {name}. '
            'Agr\u00e9guelo primero: "agregar contacto {name}"'
        ),
        "no_transactions": (
            "No se encontraron transacciones recientes para la factura. "
            "Agregue ingresos primero."
        ),
        "pdf_failed": "No se pudo generar el PDF. Intente de nuevo.",
        "invoice_ready": (
            "\U0001f4c4 <b>Factura #{number}</b>\n"
            "Cliente: {name}\n"
            "Total: {symbol}{total}\n"
            "Vencimiento: {due}"
        ),
    },
}
_CURRENCY_SYMBOLS = {"USD": "$", "EUR": "\u20ac", "GBP": "\u00a3", "RUB": "\u20bd"}
register_strings("generate_invoice_pdf", _STRINGS)


class GenerateInvoicePdfSkill:
    name = "generate_invoice_pdf"
    intents = ["generate_invoice_pdf"]
    model = "claude-sonnet-4-6"

    def get_system_prompt(self, context: SessionContext) -> str:
        return "Generate professional PDF invoices."

    @observe(name="skill_generate_invoice_pdf")
    async def execute(
        self,
        message: IncomingMessage,
        context: SessionContext,
        intent_data: dict[str, Any],
    ) -> SkillResult:
        family_id = context.family_id
        lang = context.language or "en"
        ns = "generate_invoice_pdf"
        if not family_id:
            return SkillResult(response_text=t_cached(_STRINGS, "no_account", lang, ns))

        contact_name = intent_data.get("contact_name")
        if not contact_name:
            return SkillResult(response_text=t_cached(_STRINGS, "no_contact", lang, ns))

        # Find contact
        contact = await self._find_contact(family_id, contact_name)
        if not contact:
            return SkillResult(
                response_text=t_cached(
                    _STRINGS, "contact_not_found", lang, ns
                ).format(name=contact_name)
            )

        # Get income transactions for this contact (use intent dates or default 30 days)
        transactions = await self._get_recent_transactions(
            family_id,
            contact_name=contact["name"],
            date_from=intent_data.get("date_from"),
            date_to=intent_data.get("date_to"),
        )
        if not transactions:
            return SkillResult(
                response_text=t_cached(_STRINGS, "no_transactions", lang, ns)
            )

        # Build invoice data
        today = date.today()
        due = today + timedelta(days=30)
        invoice_num = self._generate_invoice_number()
        total = sum(tx["amount"] for tx in transactions)
        currency = context.currency or "USD"
        currency_symbol = _CURRENCY_SYMBOLS.get(currency, currency + " ")

        # Get business profile info
        profile = context.profile_config
        company_name = "My Business"
        company_address = ""
        company_phone = ""
        if profile:
            company_name = getattr(profile, "business_name", None) or company_name
            company_address = getattr(profile, "address", None) or ""
            company_phone = getattr(profile, "phone", None) or ""

        # Render HTML
        env = Environment(loader=BaseLoader())
        template = env.from_string(INVOICE_HTML_TEMPLATE)
        html = template.render(
            company_name=company_name,
            company_address=company_address,
            company_phone=company_phone,
            invoice_number=invoice_num,
            invoice_date=today.strftime("%B %d, %Y"),
            due_date=due.strftime("%B %d, %Y"),
            client_name=contact["name"],
            client_email=contact.get("email", ""),
            client_phone=contact.get("phone", ""),
            currency=currency,
            currency_symbol=currency_symbol,
            items=transactions,
            total=total,
            notes="Payment due within 30 days.",
        )

        # Generate PDF with WeasyPrint (in thread to avoid blocking event loop)
        try:
            from weasyprint import HTML

            pdf_bytes = await asyncio.to_thread(HTML(string=html).write_pdf)
        except Exception:
            logger.exception("PDF generation failed")
            return SkillResult(
                response_text=t_cached(_STRINGS, "pdf_failed", lang, ns)
            )

        filename = f"invoice_{invoice_num}.pdf"
        return SkillResult(
            response_text=t_cached(
                _STRINGS, "invoice_ready", lang, ns
            ).format(
                number=invoice_num,
                name=contact["name"],
                symbol=currency_symbol,
                total=f"{total:.2f}",
                due=due.strftime("%B %d, %Y"),
            ),
            document=pdf_bytes,
            document_name=filename,
        )

    @staticmethod
    async def _find_contact(family_id: str, name: str) -> dict[str, Any] | None:
        async with async_session() as session:
            stmt = (
                select(Contact)
                .where(
                    Contact.family_id == uuid.UUID(family_id),
                    Contact.name.ilike(f"%{name}%"),
                )
                .limit(1)
            )
            result = await session.scalar(stmt)
            if not result:
                return None
            return {
                "name": result.name,
                "email": result.email,
                "phone": result.phone,
                "id": str(result.id),
            }

    @staticmethod
    async def _get_recent_transactions(
        family_id: str,
        contact_name: str,
        date_from: str | None = None,
        date_to: str | None = None,
    ) -> list[dict[str, Any]]:
        cutoff_start = (
            date.fromisoformat(date_from) if date_from else date.today() - timedelta(days=30)
        )
        cutoff_end = date.fromisoformat(date_to) if date_to else date.today()
        fid = uuid.UUID(family_id)
        async with async_session() as session:
            # Try matching by merchant name first
            stmt = (
                select(Transaction)
                .where(
                    Transaction.family_id == fid,
                    Transaction.type == TransactionType.income,
                    Transaction.date >= cutoff_start,
                    Transaction.date <= cutoff_end,
                    Transaction.merchant.ilike(f"%{contact_name}%"),
                )
                .order_by(Transaction.date.desc())
                .limit(20)
            )
            rows = (await session.scalars(stmt)).all()

            if not rows:
                # Fallback: all recent income if no merchant match
                stmt_all = (
                    select(Transaction)
                    .where(
                        Transaction.family_id == fid,
                        Transaction.type == TransactionType.income,
                        Transaction.date >= cutoff_start,
                        Transaction.date <= cutoff_end,
                    )
                    .order_by(Transaction.date.desc())
                    .limit(20)
                )
                rows = (await session.scalars(stmt_all)).all()

            return [
                {
                    "date": r.date.isoformat(),
                    "description": r.merchant or r.description or "Service",
                    "amount": float(r.amount),
                }
                for r in rows
            ]

    @staticmethod
    def _generate_invoice_number() -> str:
        today = date.today()
        short_id = uuid.uuid4().hex[:4].upper()
        return f"{today.strftime('%Y%m')}-{short_id}"


skill = GenerateInvoicePdfSkill()
