"""Generate invoice PDF skill — create professional PDF invoices."""

import logging
import uuid
from datetime import date, timedelta
from typing import Any

from jinja2 import BaseLoader, Environment
from sqlalchemy import select

from src.core.context import SessionContext
from src.core.db import async_session
from src.core.models.contact import Contact
from src.core.models.enums import TransactionType
from src.core.models.transaction import Transaction
from src.core.observability import observe
from src.gateway.types import IncomingMessage
from src.skills.base import SkillResult

logger = logging.getLogger(__name__)

INVOICE_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; font-size: 14px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
  .company { font-size: 20px; font-weight: bold; color: #2c3e50; }
  .invoice-title { font-size: 28px; color: #3498db; text-align: right; }
  .invoice-number { color: #666; text-align: right; }
  .addresses { display: flex; justify-content: space-between; margin: 20px 0 30px; }
  .address-block { width: 45%; }
  .address-block h3 { color: #2980b9; margin-bottom: 5px; font-size: 12px;
                       text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #3498db; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #ddd; }
  .amount { text-align: right; }
  .total-row { font-weight: bold; background: #ebf5fb; }
  .total-amount { font-size: 18px; color: #2c3e50; }
  .footer { margin-top: 40px; font-size: 11px; color: #999;
            border-top: 1px solid #ddd; padding-top: 10px; }
  .due-date { color: #e74c3c; font-weight: bold; }
  .qr-section { text-align: center; margin-top: 20px; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="company">{{ company_name }}</div>
      {% if company_address %}<div>{{ company_address }}</div>{% endif %}
      {% if company_phone %}<div>{{ company_phone }}</div>{% endif %}
    </div>
    <div>
      <div class="invoice-title">INVOICE</div>
      <div class="invoice-number">#{{ invoice_number }}</div>
    </div>
  </div>

  <div class="addresses">
    <div class="address-block">
      <h3>Bill To</h3>
      <div><b>{{ client_name }}</b></div>
      {% if client_email %}<div>{{ client_email }}</div>{% endif %}
      {% if client_phone %}<div>{{ client_phone }}</div>{% endif %}
    </div>
    <div class="address-block">
      <h3>Invoice Details</h3>
      <div>Date: {{ invoice_date }}</div>
      <div class="due-date">Due: {{ due_date }}</div>
      <div>Currency: {{ currency }}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Description</th>
        <th>Date</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ item.description }}</td>
        <td>{{ item.date }}</td>
        <td class="amount">{{ "%.2f"|format(item.amount) }}</td>
      </tr>
      {% endfor %}
      <tr class="total-row">
        <td colspan="3"><b>Total</b></td>
        <td class="amount total-amount"><b>{{ currency_symbol }}{{ "%.2f"|format(total) }}</b></td>
      </tr>
    </tbody>
  </table>

  {% if notes %}
  <div style="margin-top: 20px;">
    <b>Notes:</b> {{ notes }}
  </div>
  {% endif %}

  <div class="footer">
    Generated by AI Assistant — {{ invoice_date }}
  </div>
</body>
</html>"""


class GenerateInvoicePdfSkill:
    name = "generate_invoice_pdf"
    intents = ["generate_invoice_pdf"]
    model = "claude-sonnet-4-6"

    def get_system_prompt(self, context: SessionContext) -> str:
        return "Generate professional PDF invoices."

    @observe(name="skill_generate_invoice_pdf")
    async def execute(
        self,
        message: IncomingMessage,
        context: SessionContext,
        intent_data: dict[str, Any],
    ) -> SkillResult:
        family_id = context.family_id
        if not family_id:
            return SkillResult(
                response_text="Set up your account first to generate invoices."
            )

        contact_name = intent_data.get("contact_name")
        if not contact_name:
            return SkillResult(
                response_text="Who should I invoice? "
                'Try: "generate invoice PDF for Mike Chen"'
            )

        # Find contact
        contact = await self._find_contact(family_id, contact_name)
        if not contact:
            return SkillResult(
                response_text=f"I don't have {contact_name}'s info. "
                f'Add them first: "add contact {contact_name}"'
            )

        # Get recent income transactions as line items
        transactions = await self._get_recent_transactions(family_id, days=30)
        if not transactions:
            return SkillResult(
                response_text="No recent transactions found to include in the invoice. "
                "Add some income entries first."
            )

        # Build invoice data
        today = date.today()
        due = today + timedelta(days=30)
        invoice_num = self._generate_invoice_number()
        total = sum(tx["amount"] for tx in transactions)
        currency = context.currency or "USD"
        currency_symbol = "$" if currency == "USD" else currency + " "

        # Get business profile info
        profile = context.profile_config
        company_name = "My Business"
        company_address = ""
        company_phone = ""
        if profile:
            company_name = getattr(profile, "business_name", None) or company_name
            company_address = getattr(profile, "address", None) or ""
            company_phone = getattr(profile, "phone", None) or ""

        # Render HTML
        env = Environment(loader=BaseLoader())
        template = env.from_string(INVOICE_HTML_TEMPLATE)
        html = template.render(
            company_name=company_name,
            company_address=company_address,
            company_phone=company_phone,
            invoice_number=invoice_num,
            invoice_date=today.strftime("%B %d, %Y"),
            due_date=due.strftime("%B %d, %Y"),
            client_name=contact["name"],
            client_email=contact.get("email", ""),
            client_phone=contact.get("phone", ""),
            currency=currency,
            currency_symbol=currency_symbol,
            items=transactions,
            total=total,
            notes="Payment due within 30 days.",
        )

        # Generate PDF with WeasyPrint
        try:
            from weasyprint import HTML

            pdf_bytes = HTML(string=html).write_pdf()
        except Exception as e:
            logger.exception("PDF generation failed")
            return SkillResult(
                response_text=f"Failed to generate PDF: {e}"
            )

        filename = f"invoice_{invoice_num}.pdf"
        return SkillResult(
            response_text=(
                f"\U0001f4c4 <b>Invoice #{invoice_num}</b>\n"
                f"Client: {contact['name']}\n"
                f"Total: {currency_symbol}{total:.2f}\n"
                f"Due: {due.strftime('%B %d, %Y')}"
            ),
            document=pdf_bytes,
            document_name=filename,
        )

    @staticmethod
    async def _find_contact(family_id: str, name: str) -> dict[str, Any] | None:
        async with async_session() as session:
            stmt = (
                select(Contact)
                .where(
                    Contact.family_id == uuid.UUID(family_id),
                    Contact.name.ilike(f"%{name}%"),
                )
                .limit(1)
            )
            result = await session.scalar(stmt)
            if not result:
                return None
            return {
                "name": result.name,
                "email": result.email,
                "phone": result.phone,
                "id": str(result.id),
            }

    @staticmethod
    async def _get_recent_transactions(
        family_id: str, days: int = 30
    ) -> list[dict[str, Any]]:
        cutoff = date.today() - timedelta(days=days)
        async with async_session() as session:
            stmt = (
                select(Transaction)
                .where(
                    Transaction.family_id == uuid.UUID(family_id),
                    Transaction.type == TransactionType.income,
                    Transaction.date >= cutoff,
                )
                .order_by(Transaction.date.desc())
                .limit(20)
            )
            rows = (await session.scalars(stmt)).all()
            return [
                {
                    "date": r.date.isoformat(),
                    "description": r.merchant or r.description or "Service",
                    "amount": float(r.amount),
                }
                for r in rows
            ]

    @staticmethod
    def _generate_invoice_number() -> str:
        today = date.today()
        short_id = uuid.uuid4().hex[:4].upper()
        return f"{today.strftime('%Y%m')}-{short_id}"


skill = GenerateInvoicePdfSkill()
