from collections.abc import Awaitable, Callable
from typing import Protocol

from src.gateway.types import IncomingMessage, OutgoingMessage


class MessageGateway(Protocol):
    """Abstract transport interface. Implementations: Telegram, WhatsApp, etc."""

    channel_type: str

    async def send(self, message: OutgoingMessage) -> None: ...

    async def send_typing(self, chat_id: str) -> None: ...

    async def send_document(self, chat_id: str, document: bytes, filename: str) -> None: ...

    async def send_photo(self, chat_id: str, photo: bytes | str) -> None: ...

    async def edit_message(self, chat_id: str, message_id: str, new_text: str) -> None: ...

    def on_message(self, handler: Callable[[IncomingMessage], Awaitable[None]]) -> None: ...

    async def start(self) -> None: ...

    async def stop(self) -> None: ...
